pipeline {
    agent any
    
    environment {
        REPO_URL = 'git@github.com:nishantindorkar/express.git'
        DOCKER_IMAGE = 'hello-world-app'
        DOCKER_TAG = 'latest'
        CONT_NAME = 'express-app'
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout from Git') {
            steps {
                git branch: 'master',credentialsId: 'jenkins',url: "${REPO_URL}"
            }
        }

        stage("Docker Build & Push"){
            steps{
                script{
                   withDockerRegistry(credentialsId: 'docker', url: 'https://index.docker.io/v1/'){   
                       sh "docker stop ${CONT_NAME} || true && docker rm ${CONT_NAME} || true"
                       sh "docker rmi ${DOCKER_IMAGE}"
                       sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ${WORKSPACE}/examples/hello-world/"
                       sh "docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} nishantindorkar/${DOCKER_IMAGE}:${DOCKER_TAG}"
                       sh "docker push nishantindorkar/${DOCKER_IMAGE}:${DOCKER_TAG} "
                       sh "docker images"
                    }
                }
            }
        }

        stage('Deploy to container'){
            steps{
                 script {
                    //sh "docker stop ${DOCKER_IMAGE} || true && docker rm ${DOCKER_IMAGE} || true"
                    sh "docker run --name ${CONT_NAME} -p 3000:8080 nishantindorkar/${DOCKER_IMAGE}:${DOCKER_TAG}"
                }
            }
        }    
    }
}
