pipeline {
    agent any
    
    environment {
        REPO_URL = 'git@github.com:nishantindorkar/express.git'
        DOCKER_IMAGE = 'hello-world-app'
        DOCKER_TAG = 'latest'
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout from Git') {
            steps {
                git branch: 'master',credentialsId: 'jenkins',url: "${REPO_URL}"
            }
        }

        stage("Docker Build & Push"){
            steps{
                script{
                   withDockerRegistry(credentialsId: 'docker', url: 'https://index.docker.io/v1/'){   
                       sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} -f ${WORKSPACE}/Dockerfile ."
                       sh "docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} nishantindorkar/${DOCKER_IMAGE}:${DOCKER_TAG}"
                       sh "docker push nishantindorkar/${DOCKER_IMAGE}:${DOCKER_TAG} "
                    }
                }
            }
        }    
    }
}
